name: Security Scanning

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]
  schedule:
    # Run weekly security scans
    - cron: '0 0 * * 1'

jobs:
  codeql-analyze:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  dependency-review:
    name: Dependency Security Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'staging')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD, Unlicense

  npm-audit:
    name: NPM Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run NPM Audit
        run: |
          echo "Running npm audit..."
          npm audit --audit-level=moderate || echo "Moderate vulnerabilities found"
          
      - name: Check for High Severity Issues
        run: |
          echo "Checking for high/critical vulnerabilities..."
          AUDIT_EXIT_CODE=0
          npm audit --audit-level=high || AUDIT_EXIT_CODE=$?
          
          if [ $AUDIT_EXIT_CODE -eq 0 ]; then
            echo "✅ No high/critical vulnerabilities found"
          else
            echo "⚠️ High/critical vulnerabilities detected"
            npm audit --audit-level=high
            echo "Please review and fix vulnerabilities before proceeding"
            exit 1
          fi

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified